In [1]:
import numpy as np

**Q1: Write a NumPy program to test whether none of the elements of a given array is zero**

In [17]:
def is_all_nonzero(np_arr):
    return (np_arr).all() # or (np_arr != 0).all() or np.all(np_arr) or np.all(np_arr != 0)

In [18]:
with_zero = np.arange(6)
without_zero = np.arange(1,7)
print(is_all_nonzero(with_zero))
print(is_all_nonzero(without_zero))

False
True


**Q2: Write a NumPy program to test whether any of the elements of a given array is non-zero**

In [19]:
def any_nonzero(np_arr):
    return (np_arr).any() # or (np.arr != 0).any() or np.any(np_arr) or np.any(np_arr != 0)

In [20]:
all_zero = np.zeros(6)
some_non_zero = np.arange(6)
print(any_nonzero(all_zero))
print(any_nonzero(some_non_zero))

False
True


**Q3: Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)**

In [117]:
# Note: np.nan == np.nan returns False
def is_any_infinite(np_arr):
#     is_inf = (np.isnan(np_arr)) | (np_arr == np.inf)
    is_inf = ~np.isfinite(np_arr) # using built-in function, Nite: "isfinite checks for both  Not infinity or nan"
    return is_inf

In [119]:
with_inf = np.array([1,2,np.inf,4])
with_NaN = np.array([1,2,np.nan,4])
int_arr = np.arange(4)
print(is_any_infinite(with_inf))
print(is_any_infinite(with_NaN))
print(is_any_infinite(int_arr))

[False False  True False]
[False False  True False]
[False False False False]


**Q4:  Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.**

In [114]:
def compare(np_arr1, np_arr2):
    print("equality", np_arr1 == np_arr2)
    print("less", np_arr1 < np_arr2)
    print("less equal", np_arr1 <= np_arr2)
    print("greater", np_arr1 > np_arr2)
    print("greater equal", np_arr1 >= np_arr2)

In [120]:
x = np.array([3, 5])
y = np.array([2, 5])
compare(x, y)

equality [False  True]
less [False False]
less equal [False  True]
greater [ True False]
greater equal [ True  True]


**Q5: Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.**

In [123]:
np_arr = np.array([1,7,13,105])
np_arr.itemsize * np_arr.size

16

**Q6: Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives**

In [127]:
arr = np.empty(30)
arr[:10] = 0
arr[10:20] = 1
arr[20:30] = 5
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [130]:
# or
arr = np.array([np.zeros(10), np.ones(10), np.full(10, fill_value=5)]).flatten()
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Q7: Write a NumPy program to create an array of the integers from 30 to70**

In [133]:
arr = np.arange(30,71) # or np.array(range(30,71))
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

**Q8: Write a NumPy program to create an array of all the even integers from 30 to 70**

In [134]:
arr = np.arange(30,71, 2) # or np.array(range(30,71,2))
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

**Q9: Write a NumPy program to create a 3x3 identity matrix**

In [138]:
id_arr = np.identity(3)
# id_arr = np.eye(3) # or np.eye(N=3, M=3)
id_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Q10: Write a NumPy program to create a 3X4 array using and iterate over it**

In [144]:
np_arr = np.arange(12).reshape((3,4))
for val in np.nditer(np_arr):
    print(val, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

**Q11: Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50**

In [145]:
arr = np.linspace(5,50,10) #Note this will include 50 as well
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

**Q12: Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.**

In [150]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [154]:
arr = np.zeros((10,10))
arr[[0,-1]] = 1
arr[:, [0,-1]] = 1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Q13: Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.**

In [156]:
arr = np.diag([1, 2, 3, 4, 5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**Q14: Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.**

In [158]:
arr = np.arange(30).reshape((3,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [159]:
arr.sum(axis = 0) # or np.sum(arr, axis = 0)

array([30, 33, 36, 39, 42, 45, 48, 51, 54, 57])

In [161]:
arr.sum(axis = 1) # or np.sum(arr, axis = 1)

array([ 45, 145, 245])

**Q15: Write a NumPy program to add a vector to each row of a given matrix.**

In [162]:
matrix = np.arange(30).reshape((3,10))
arr = np.arange(10)
matrix + arr

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

**Q16: Write a NumPy program to convert an array to a float type**

In [164]:
arr = np.arange(5)
arr.astype("float")

array([0., 1., 2., 3., 4.])

**Q17: Stack arrays a and b vertically**

In [6]:
# for vertical stacking, no of columns should be same
a = np.arange(10).reshape(2,5)
b = np.arange(10, 30).reshape(4,5)
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

**Q18: How to stack two arrays horizontally?**

In [7]:
# for horizontal stacking no of rows should be same
a = np.arange(10).reshape(2,5)
b = np.arange(10, 30).reshape(2,10)
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**Q19: How to get the common items between two python numpy arrays?**

In [9]:
a = np.arange(10).reshape(2,5)
b = np.arange(0,20,2)
np.intersect1d(a,b) # firstly flats the two arrays

array([0, 2, 4, 6, 8])

**Q20: How to remove from one array those items that exist in another?**

In [13]:
a = np.arange(10).reshape(2,5)
b = np.arange(0,20,2)
np.setdiff1d(a,b) # returns a - b

array([1, 3, 5, 7, 9])

**Q21: Write a program to give element-wise maximum of the two arrays**

In [20]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
np.maximum(a,b)

array([6, 7, 9, 8, 9, 7, 5])

**Q22: How to swap two columns in a 2d numpy array?**

In [26]:
arr =np.arange(10).reshape(2,5)
print(arr)
arr[:,[1,2]] = arr[:, [2,1]] #swap 2nd column with 3rd
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 2 1 3 4]
 [5 7 6 8 9]]


**Q23: How to swap two rows in a 2d numpy array?**

In [25]:
arr =np.arange(10).reshape(2,5)
print(arr)
arr[[0,1]] = arr[[1,0]] #swap 1st row with 2nd
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]


**Q24: How to compute the mean, median, standard deviation of a numpy array?**

In [29]:
arr =np.arange(15).reshape(3,5)
print(np.mean(arr[:5]))
print(np.median(arr[:5]))
np.std(arr[:5])

7.0
7.0


4.320493798938574

**Q25: How to find the percentile scores of a numpy array?**

In [30]:
arr =np.arange(15).reshape(3,5)
np.percentile(arr, q=[25,50,75])

array([ 3.5,  7. , 10.5])

**Q26: How to insert values at random positions in an array?**

In [34]:
arr =np.arange(15).reshape(3,5)
np.insert(arr, 1, 99, axis=1)

array([[ 0, 99,  1,  2,  3,  4],
       [ 5, 99,  6,  7,  8,  9],
       [10, 99, 11, 12, 13, 14]])

**Q27:  How to find the position of missing values in numpy array?**

In [37]:
arr = np.array([1,np.nan,2,3,np.nan,5])
np.where(np.isnan(arr))

(array([1, 4], dtype=int64),)

**Q28: stack two arrays in depth**

In [40]:
arr =np.arange(15).reshape(3,5)
arr1 =np.arange(15, 30).reshape(3,5)
print(arr)
print("\n", arr1)
np.dstack((arr,arr1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([[[ 0, 15],
        [ 1, 16],
        [ 2, 17],
        [ 3, 18],
        [ 4, 19]],

       [[ 5, 20],
        [ 6, 21],
        [ 7, 22],
        [ 8, 23],
        [ 9, 24]],

       [[10, 25],
        [11, 26],
        [12, 27],
        [13, 28],
        [14, 29]]])